2020-12-01 19:33:02,686 ERROR 18283 [-/127.0.0.1/-/10989ms GET /skeleton?url=https://h5-test.baoyun18.com/m/productForMixin/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.Error: Evaluation failed: TypeError: Cannot read property 'genSkeleton' of undefined
    at __puppeteer_evaluation_script__:2:28
    at __puppeteer_evaluation_script__:2:28
    at ExecutionContext._evaluateInternal (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/DOMWorld.js:112:20)
  -- ASYNC --
    at Frame.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at getSkeleton (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/getSkeleton.js:45:14)

pid: 18283
hostname: caoyouzhi.local

2020-12-01 19:37:35,198 ERROR 20189 [-/127.0.0.1/-/10ms GET /skeleton?url=https://h5-test.baoyun18.com/m/productForMixin/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.ReferenceError: autoSkeleton is not defined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:39:5)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 20189
hostname: caoyouzhi.local

2020-12-01 19:39:23,874 ERROR 20641 [-/127.0.0.1/-/7633ms GET /skeleton?url=https://h5-test.baoyun18.com/m/productForMixin/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.Error: Evaluation failed: TypeError: Cannot read property 'genSkeleton' of undefined
    at __puppeteer_evaluation_script__:2:28
    at __puppeteer_evaluation_script__:2:28
    at ExecutionContext._evaluateInternal (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/DOMWorld.js:112:20)
  -- ASYNC --
    at Frame.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at Object.getSkeleton (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/getSkeleton.js:45:14)

pid: 20641
hostname: caoyouzhi.local

2020-12-01 19:43:35,876 ERROR 21793 [-/127.0.0.1/-/7787ms GET /skeleton?url=https://h5-test.baoyun18.com/m/productForMixin/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.Error: Evaluation failed: TypeError: Cannot read property 'genSkeleton' of undefined
    at __puppeteer_evaluation_script__:2:28
    at __puppeteer_evaluation_script__:2:28
    at ExecutionContext._evaluateInternal (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/DOMWorld.js:112:20)
  -- ASYNC --
    at Frame.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at getSkeleton (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/getSkeleton.js:45:14)

pid: 21793
hostname: caoyouzhi.local

2020-12-01 19:50:35,956 ERROR 23696 [-/127.0.0.1/-/6298ms GET /skeleton?url=https://h5-test.baoyun18.com/m/productForMixin/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.Error: Evaluation failed: TypeError: Cannot read property 'genSkeleton' of undefined
    at __puppeteer_evaluation_script__:2:28
    at __puppeteer_evaluation_script__:2:28
    at ExecutionContext._evaluateInternal (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/DOMWorld.js:112:20)
  -- ASYNC --
    at Frame.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at getSkeleton (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/getSkeleton.js:45:14)

pid: 23696
hostname: caoyouzhi.local

2020-12-01 19:53:51,781 ERROR 24609 [-/127.0.0.1/-/10651ms GET /skeleton?url=https://h5-test.baoyun18.com/m/productForMixin/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/skeletonTemplate/m.productForMixin.list.html'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at insertSkeleton (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/insertSkeleton.js:92:6)
    at getSkeleton (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/getSkeleton.js:57:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
errno: -2
syscall: "open"
code: "ENOENT"
path: "/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/skeletonTemplate/m.productForMixin.list.html"
name: "ENOENTError"
pid: 24609
hostname: caoyouzhi.local

2020-12-01 20:01:21,967 ERROR 26371 [-/127.0.0.1/-/10965ms GET /skeleton?url=https://h5-test.baoyun18.com/m/productForMixin/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/skeletonTemplate/m.productForMixin.list.html'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at insertSkeleton (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/insertSkeleton.js:92:6)
    at getSkeleton (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/getSkeleton.js:57:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
errno: -2
syscall: "open"
code: "ENOENT"
path: "/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/skeletonTemplate/m.productForMixin.list.html"
name: "ENOENTError"
pid: 26371
hostname: caoyouzhi.local

2020-12-01 20:32:38,337 ERROR 34201 [-/127.0.0.1/-/8443ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:27:32)

pid: 34201
hostname: caoyouzhi.local

2020-12-01 20:42:12,818 ERROR 34358 [-/127.0.0.1/-/8877ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:25:32)

pid: 34358
hostname: caoyouzhi.local

2020-12-01 20:42:58,076 ERROR 34358 [-/127.0.0.1/-/8195ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:25:32)

pid: 34358
hostname: caoyouzhi.local

2020-12-01 20:44:09,198 ERROR 34358 [-/127.0.0.1/-/8105ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:25:32)

pid: 34358
hostname: caoyouzhi.local

2020-12-01 20:46:59,834 ERROR 34358 [-/127.0.0.1/-/13955ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:25:32)

pid: 34358
hostname: caoyouzhi.local

2020-12-01 20:48:08,806 ERROR 34358 [-/127.0.0.1/-/12842ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:25:32)

pid: 34358
hostname: caoyouzhi.local

2020-12-01 20:48:41,699 ERROR 38395 [-/127.0.0.1/-/10176ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:25:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 38395
hostname: caoyouzhi.local

2020-12-01 20:49:22,364 ERROR 38395 [-/127.0.0.1/-/9580ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:25:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 38395
hostname: caoyouzhi.local

2020-12-01 20:49:38,387 ERROR 38605 [-/127.0.0.1/-/10043ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:26:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 38605
hostname: caoyouzhi.local

2020-12-01 20:50:10,233 ERROR 38689 [-/127.0.0.1/-/10478ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: Cannot read property 'img' of undefined
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:26:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 38689
hostname: caoyouzhi.local

2020-12-01 21:00:25,467 ERROR 40398 [-/127.0.0.1/-/12ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: skeletonUrl.search.split is not a function
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:24:42)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 40398
hostname: caoyouzhi.local

2020-12-01 21:00:27,074 ERROR 40398 [-/127.0.0.1/-/4ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: skeletonUrl.search.split is not a function
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:24:42)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 40398
hostname: caoyouzhi.local

2020-12-01 21:00:28,593 ERROR 40398 [-/127.0.0.1/-/0ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: skeletonUrl.search.split is not a function
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:24:42)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 40398
hostname: caoyouzhi.local

2020-12-01 21:00:41,348 ERROR 40398 [-/127.0.0.1/-/1ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: skeletonUrl.search.split is not a function
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:24:42)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 40398
hostname: caoyouzhi.local

2020-12-01 21:00:42,212 ERROR 40398 [-/127.0.0.1/-/1ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: skeletonUrl.search.split is not a function
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:24:42)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 40398
hostname: caoyouzhi.local

2020-12-01 21:00:42,577 ERROR 40398 [-/127.0.0.1/-/1ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: skeletonUrl.search.split is not a function
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:24:42)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 40398
hostname: caoyouzhi.local

2020-12-01 21:00:42,911 ERROR 40398 [-/127.0.0.1/-/1ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: skeletonUrl.search.split is not a function
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:24:42)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 40398
hostname: caoyouzhi.local

2020-12-01 21:01:12,973 ERROR 41384 [-/127.0.0.1/-/14ms GET /skeleton?url=https://h5-test.baoyun18.com/m/order/list?uniqueId=C4Ip843YBqgB9K7OXAYmib&partner=1111&code=0] nodejs.TypeError: skeletonUrl.search.split is not a function
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:24:42)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 41384
hostname: caoyouzhi.local

2020-12-02 09:24:57,142 ERROR 41370 nodejs.ClusterClientNoResponseError: client no response in 43271548ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 41370
hostname: caoyouzhi.local

2020-12-02 09:51:05,687 ERROR 41370 nodejs.ClusterClientNoResponseError: client no response in 1568540ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 41370
hostname: caoyouzhi.local

2020-12-02 14:09:02,624 ERROR 91382 [-/127.0.0.1/-/13ms GET /skeleton/home] nodejs.TypeError: Cannot read property 'split' of null
    at SkeletonController.index (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:26:36)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:36:12

pid: 91382
hostname: caoyouzhi.local

2020-12-02 14:44:24,454 ERROR 1960 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 1960
hostname: caoyouzhi.local

2020-12-02 14:44:52,699 ERROR 1960 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 1960
hostname: caoyouzhi.local

2020-12-02 14:45:39,578 ERROR 2294 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 2294
hostname: caoyouzhi.local

2020-12-02 14:47:51,586 ERROR 2880 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 2880
hostname: caoyouzhi.local

2020-12-02 14:47:52,799 ERROR 2880 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 2880
hostname: caoyouzhi.local

2020-12-02 14:47:53,164 ERROR 2880 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 2880
hostname: caoyouzhi.local

2020-12-02 14:47:53,619 ERROR 2880 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 2880
hostname: caoyouzhi.local

2020-12-02 14:47:56,311 ERROR 2880 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 2880
hostname: caoyouzhi.local

2020-12-02 14:49:44,452 ERROR 3439 nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/view/skeleton.nj
    at ContextView.[contextView#render] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 3439
hostname: caoyouzhi.local

2020-12-02 16:25:50,171 ERROR 29132 nodejs.BadRequestError: Content-Type must be multipart/*
    at Object.throw (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa@2.13.0@koa/lib/context.js:97:11)
    at Object.multipart (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-multipart@2.10.3@egg-multipart/app/extend/context.js:167:17)
    at Object.getFileStream (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-multipart@2.10.3@egg-multipart/app/extend/context.js:215:24)
    at SkeletonController.getImage (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:39:21)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_@eggjs_router@2.0.0@@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)
message: "Content-Type must be multipart/*"
pid: 29132
hostname: caoyouzhi.local

2020-12-02 16:41:25,900 ERROR 32886 [-/127.0.0.1/-/8739ms POST /skeleton/getImage] nodejs.SyntaxError: Unexpected token i in JSON at position 1
    at JSON.parse (<anonymous>)
    at SkeletonController.getImage (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/app/controller/skeleton.js:42:21)

pid: 32886
hostname: caoyouzhi.local

2020-12-02 16:41:59,663 ERROR 33165 [-/127.0.0.1/-/1174ms POST /skeleton/getImage] nodejs.Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at Promise (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Connection.js:182:12)
    at navigate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/FrameManager.js:118:39)
    at FrameManager.navigateFrame (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/FrameManager.js:95:7)
    at Frame.goto (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/FrameManager.js:406:37)
    at Frame.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at Page.goto (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at openPage (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/openPage.js:41:14)
  -- ASYNC --
    at Frame.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at openPage (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/openPage.js:41:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Protocol error (Page.navigate): Cannot navigate to invalid URL"
pid: 33165
hostname: caoyouzhi.local

2020-12-02 16:42:05,111 ERROR 33201 [-/127.0.0.1/-/1042ms POST /skeleton/getImage] nodejs.Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at Promise (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Connection.js:182:12)
    at navigate (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/FrameManager.js:118:39)
    at FrameManager.navigateFrame (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/FrameManager.js:95:7)
    at Frame.goto (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/FrameManager.js:406:37)
    at Frame.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at Page.goto (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at openPage (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/openPage.js:41:14)
  -- ASYNC --
    at Frame.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/node_modules/_puppeteer@1.20.0@puppeteer/lib/helper.js:112:23)
    at openPage (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/auto-skeleton/src/openPage.js:41:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
message: "Protocol error (Page.navigate): Cannot navigate to invalid URL"
pid: 33201
hostname: caoyouzhi.local

2020-12-02 18:57:09,140 ERROR 4528 nodejs.ClusterClientNoResponseError: client no response in 945967ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 4528
hostname: caoyouzhi.local

2020-12-03 12:38:42,035 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 1837080ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 14:51:01,158 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 2257886ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 14:54:52,214 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 231054ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 15:34:24,573 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 2331592ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 15:55:32,614 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 1228020ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 16:42:00,437 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 2767819ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 18:56:12,414 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 390450ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 19:00:07,175 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 194739ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 19:31:05,652 ERROR 6247 nodejs.ClusterClientNoResponseError: client no response in 318239ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 6247
hostname: caoyouzhi.local

2020-12-03 21:59:39,546 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 1761272ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-03 22:37:59,717 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 2260125ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-03 22:59:06,888 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 606964ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-03 23:31:58,498 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 1931583ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-03 23:58:59,795 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 1601281ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 00:59:22,593 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 3582784ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 01:59:09,498 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 3546879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 02:59:14,305 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 3584789ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 03:58:24,434 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 3510109ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 04:53:28,601 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 3264148ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 04:58:05,706 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 257090ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 05:58:35,832 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 3590120ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 07:59:04,042 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 3550074ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 08:58:38,153 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 3554101ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

2020-12-04 09:38:45,236 ERROR 21454 nodejs.ClusterClientNoResponseError: client no response in 2367064ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/iyb-caoyouzhi/Desktop/iyb-new-code/url2skeleton/server/init/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 21454
hostname: caoyouzhi.local

